// Mock data for Phase 1 (UI only). Shaped exactly like the future database rows,
// so components can later read from Supabase instead without changes.
// One diploma student in DP2 (exams May 2027), 6 subjects, and a mix of tasks.

import type { Profile, Subject, Task } from "@/types";

const USER_ID = "user_2mockHaya7Qx9";

export const mockProfile: Profile = {
  id: USER_ID,
  name: "Haya",
  graduation_year: 2027,
  diploma: true,
  onboarding_complete: true,
};

export const mockSubjects: Subject[] = [
  {
    id: "sub_biology",
    user_id: USER_ID,
    name: "Biology",
    level: "HL",
    color: "#62AD59",
    predicted_grade: 6,
    min_hours_week: 4,
    max_hours_week: 6,
    study_days: [0, 2, 4],
  },
  {
    id: "sub_chemistry",
    user_id: USER_ID,
    name: "Chemistry",
    level: "HL",
    color: "#4A7FD4",
    predicted_grade: 5,
    min_hours_week: 5,
    max_hours_week: 7,
    study_days: [1, 3, 5],
  },
  {
    id: "sub_economics",
    user_id: USER_ID,
    name: "Economics",
    level: "HL",
    color: "#E0A030",
    predicted_grade: 6,
    min_hours_week: 3,
    max_hours_week: 5,
    study_days: [1, 4, 6],
  },
  {
    id: "sub_english",
    user_id: USER_ID,
    name: "English A: Language and Literature",
    level: "SL",
    color: "#9B6BC8",
    predicted_grade: 6,
    min_hours_week: 2,
    max_hours_week: 3,
    study_days: [2, 6],
  },
  {
    id: "sub_spanish",
    user_id: USER_ID,
    name: "Spanish B",
    level: "SL",
    color: "#D9534F",
    predicted_grade: 5,
    min_hours_week: 2,
    max_hours_week: 3,
    study_days: [0, 3],
  },
  {
    id: "sub_math",
    user_id: USER_ID,
    name: "Mathematics: Analysis and Approaches",
    level: "SL",
    color: "#2BA5A0",
    predicted_grade: 5,
    min_hours_week: 3,
    max_hours_week: 4,
    study_days: [1, 2, 4, 5],
  },
];

export const mockTasks: Task[] = [
  {
    id: "task_01",
    user_id: USER_ID,
    subject_id: "sub_biology",
    title: "Biology IA first draft",
    type: "IA",
    due_date: "2026-10-09",
    status: "In progress",
    priority: "High",
    notes: "Results and analysis sections still missing. Check uncertainty calculations.",
  },
  {
    id: "task_02",
    user_id: USER_ID,
    subject_id: "sub_chemistry",
    title: "Chemistry IA final submission",
    type: "IA",
    due_date: "2026-11-20",
    status: "Not started",
    priority: "High",
    notes: null,
  },
  {
    id: "task_03",
    user_id: USER_ID,
    subject_id: "sub_economics",
    title: "Economics IA commentary 3",
    type: "IA",
    due_date: "2026-10-16",
    status: "In progress",
    priority: "Medium",
    notes: "Need an article on macroeconomics, published within the last year.",
  },
  {
    id: "task_04",
    user_id: USER_ID,
    subject_id: "sub_math",
    title: "Math IA exploration draft",
    type: "IA",
    due_date: "2026-12-04",
    status: "Not started",
    priority: "Medium",
    notes: null,
  },
  {
    id: "task_05",
    user_id: USER_ID,
    subject_id: "sub_biology",
    title: "EE full draft to supervisor",
    type: "EE",
    due_date: "2026-10-23",
    status: "In progress",
    priority: "High",
    notes: "Aim for 3,500 words. Supervisor wants it printed.",
  },
  {
    id: "task_06",
    user_id: USER_ID,
    subject_id: "sub_biology",
    title: "EE second reflection (RPPF)",
    type: "EE",
    due_date: "2026-11-06",
    status: "Not started",
    priority: "Low",
    notes: null,
  },
  {
    id: "task_07",
    user_id: USER_ID,
    subject_id: null,
    title: "TOK exhibition",
    type: "TOK",
    due_date: "2026-09-18",
    status: "Completed",
    priority: "Medium",
    notes: null,
  },
  {
    id: "task_08",
    user_id: USER_ID,
    subject_id: null,
    title: "TOK essay outline",
    type: "TOK",
    due_date: "2026-10-12",
    status: "Not started",
    priority: "High",
    notes: "Chose prescribed title 3.",
  },
  {
    id: "task_09",
    user_id: USER_ID,
    subject_id: null,
    title: "CAS reflection for beach clean-up",
    type: "CAS",
    due_date: "2026-10-05",
    status: "Not started",
    priority: "Low",
    notes: null,
  },
  {
    id: "task_10",
    user_id: USER_ID,
    subject_id: null,
    title: "CAS project evidence upload",
    type: "CAS",
    due_date: "2026-11-30",
    status: "In progress",
    priority: "Medium",
    notes: "Photos and meeting notes from the tutoring club.",
  },
  {
    id: "task_11",
    user_id: USER_ID,
    subject_id: "sub_chemistry",
    title: "Chemistry test: Organic chemistry",
    type: "Test",
    due_date: "2026-10-02",
    status: "In progress",
    priority: "High",
    notes: null,
  },
  {
    id: "task_12",
    user_id: USER_ID,
    subject_id: "sub_spanish",
    title: "Spanish B individual oral practice",
    type: "Test",
    due_date: "2026-10-14",
    status: "Not started",
    priority: "Medium",
    notes: null,
  },
  {
    id: "task_13",
    user_id: USER_ID,
    subject_id: null,
    title: "Finish personal statement",
    type: "University",
    due_date: "2026-10-10",
    status: "In progress",
    priority: "High",
    notes: "Counselor feedback on draft 2 due back this week.",
  },
  {
    id: "task_14",
    user_id: USER_ID,
    subject_id: null,
    title: "Request teacher references",
    type: "University",
    due_date: "2026-09-25",
    status: "Completed",
    priority: "Medium",
    notes: null,
  },
  {
    id: "task_15",
    user_id: USER_ID,
    subject_id: "sub_math",
    title: "Review calculus past paper questions",
    type: "Study",
    due_date: "2026-10-07",
    status: "Not started",
    priority: "Low",
    notes: null,
  },
];
