// Mock data for Phase 1 (UI only). Shaped exactly like the future database rows,
// so components can later read from Supabase instead without changes.
// One diploma student in DP2 (exams May 2027), 6 subjects, and a mix of tasks.
// Haya's weekend is Friday and Saturday. Both plan 270 study minutes, over the
// 240-minute daily cap, so the scheduler's cap rule has something to do.

import type {
  Assessment,
  Extracurricular,
  Profile,
  StudyLog,
  Subject,
  Task,
} from "@/types";

const USER_ID = "user_2mockHaya7Qx9";

export const mockProfile: Profile = {
  id: USER_ID,
  name: "Haya",
  graduation_year: 2027,
  diploma: true,
  onboarding_complete: true,
  daily_cap_minutes: 240,
  weekend_days: [5, 6],
};

export const mockSubjects: Subject[] = [
  {
    id: "sub_math",
    user_id: USER_ID,
    name: "Mathematics: Analysis and Approaches",
    level: "HL",
    color: "#2BA5A0",
    predicted_grade: 6,
    session_minutes: 90,
    study_days: [0, 1, 2, 3, 4, 5, 6],
    priority: "High",
  },
  {
    id: "sub_physics",
    user_id: USER_ID,
    name: "Physics",
    level: "HL",
    color: "#4A7FD4",
    predicted_grade: 5,
    session_minutes: 60,
    study_days: [1, 3, 5],
    priority: "Medium",
  },
  {
    id: "sub_chemistry",
    user_id: USER_ID,
    name: "Chemistry",
    level: "HL",
    color: "#D9534F",
    predicted_grade: 5,
    session_minutes: 60,
    study_days: [2, 4, 6],
    priority: "Medium",
  },
  {
    id: "sub_economics",
    user_id: USER_ID,
    name: "Economics",
    level: "SL",
    color: "#E0A030",
    predicted_grade: 6,
    session_minutes: 60,
    study_days: [0, 2, 4],
    priority: "Medium",
  },
  {
    id: "sub_arabic",
    user_id: USER_ID,
    name: "Arabic A: Language and Literature",
    level: "SL",
    color: "#C2649A",
    predicted_grade: 7,
    session_minutes: 60,
    study_days: [5, 6],
    priority: "Low",
  },
  {
    id: "sub_english",
    user_id: USER_ID,
    name: "English A: Language and Literature",
    level: "SL",
    color: "#9B6BC8",
    predicted_grade: 6,
    session_minutes: 60,
    study_days: [5, 6],
    priority: "Low",
  },
];

export const mockTasks: Task[] = [
  {
    id: "task_01",
    user_id: USER_ID,
    subject_id: "sub_physics",
    title: "Physics IA first draft",
    type: "IA",
    due_date: "2026-10-09",
    status: "In progress",
    priority: "High",
    notes: "Results and analysis sections still missing. Check uncertainty calculations.",
  },
  {
    id: "task_02",
    user_id: USER_ID,
    subject_id: "sub_chemistry",
    title: "Chemistry IA final submission",
    type: "IA",
    due_date: "2026-11-20",
    status: "Not started",
    priority: "High",
    notes: null,
  },
  {
    id: "task_03",
    user_id: USER_ID,
    subject_id: "sub_economics",
    title: "Economics IA commentary 3",
    type: "IA",
    due_date: "2026-10-16",
    status: "In progress",
    priority: "Medium",
    notes: "Need an article on macroeconomics, published within the last year.",
  },
  {
    id: "task_04",
    user_id: USER_ID,
    subject_id: "sub_math",
    title: "Math IA exploration draft",
    type: "IA",
    due_date: "2026-12-04",
    status: "Not started",
    priority: "Medium",
    notes: null,
  },
  {
    id: "task_05",
    user_id: USER_ID,
    subject_id: "sub_physics",
    title: "EE full draft to supervisor",
    type: "EE",
    due_date: "2026-10-23",
    status: "In progress",
    priority: "High",
    notes: "Aim for 3,500 words. Supervisor wants it printed.",
  },
  {
    id: "task_06",
    user_id: USER_ID,
    subject_id: "sub_physics",
    title: "EE second reflection (RPPF)",
    type: "EE",
    due_date: "2026-11-06",
    status: "Not started",
    priority: "Low",
    notes: null,
  },
  {
    id: "task_07",
    user_id: USER_ID,
    subject_id: null,
    title: "TOK exhibition",
    type: "TOK",
    due_date: "2026-09-18",
    status: "Completed",
    priority: "Medium",
    notes: null,
  },
  {
    id: "task_08",
    user_id: USER_ID,
    subject_id: null,
    title: "TOK essay outline",
    type: "TOK",
    due_date: "2026-10-12",
    status: "Not started",
    priority: "High",
    notes: "Chose prescribed title 3.",
  },
  {
    id: "task_09",
    user_id: USER_ID,
    subject_id: null,
    title: "CAS reflection for beach clean-up",
    type: "CAS",
    due_date: "2026-10-05",
    status: "Not started",
    priority: "Low",
    notes: null,
  },
  {
    id: "task_10",
    user_id: USER_ID,
    subject_id: null,
    title: "CAS project evidence upload",
    type: "CAS",
    due_date: "2026-11-30",
    status: "In progress",
    priority: "Medium",
    notes: "Photos and meeting notes from the tutoring club.",
  },
  {
    id: "task_11",
    user_id: USER_ID,
    subject_id: "sub_chemistry",
    title: "Chemistry exam: Organic chemistry",
    type: "Exam",
    due_date: "2026-10-02",
    status: "In progress",
    priority: "High",
    notes: null,
  },
  {
    id: "task_12",
    user_id: USER_ID,
    subject_id: "sub_arabic",
    title: "Arabic Paper 1 practice exam",
    type: "Exam",
    due_date: "2026-10-14",
    status: "Not started",
    priority: "Medium",
    notes: null,
  },
  {
    id: "task_13",
    user_id: USER_ID,
    subject_id: null,
    title: "Finish personal statement",
    type: "University",
    due_date: "2026-10-10",
    status: "In progress",
    priority: "High",
    notes: "Counselor feedback on draft 2 due back this week.",
  },
  {
    id: "task_14",
    user_id: USER_ID,
    subject_id: null,
    title: "Request teacher references",
    type: "University",
    due_date: "2026-09-25",
    status: "Completed",
    priority: "Medium",
    notes: null,
  },
  {
    id: "task_15",
    user_id: USER_ID,
    subject_id: "sub_math",
    title: "Review calculus past paper questions",
    type: "Study",
    due_date: "2026-10-07",
    status: "Not started",
    priority: "Low",
    notes: null,
  },
  {
    id: "task_16",
    user_id: USER_ID,
    subject_id: "sub_physics",
    title: "Physics IA research question approved",
    type: "IA",
    due_date: "2026-09-11",
    status: "Completed",
    priority: "Medium",
    notes: null,
  },
  {
    id: "task_17",
    user_id: USER_ID,
    subject_id: "sub_physics",
    title: "Physics IA data collection",
    type: "IA",
    due_date: "2026-09-25",
    status: "Completed",
    priority: "High",
    notes: null,
  },
  {
    id: "task_18",
    user_id: USER_ID,
    subject_id: "sub_physics",
    title: "Physics IA final submission",
    type: "IA",
    due_date: "2026-11-13",
    status: "Not started",
    priority: "High",
    notes: null,
  },
];

export const mockAssessments: Assessment[] = [
  {
    id: "asm_01",
    user_id: USER_ID,
    subject_id: "sub_physics",
    name: "Unit test: Mechanics",
    date: "2026-02-12",
    score: 38,
    max_score: 45,
  },
  {
    id: "asm_02",
    user_id: USER_ID,
    subject_id: "sub_physics",
    name: "Paper 2 practice",
    date: "2026-05-20",
    score: 52,
    max_score: 90,
  },
  {
    id: "asm_03",
    user_id: USER_ID,
    subject_id: "sub_physics",
    name: "Unit test: Thermal physics",
    date: "2026-09-10",
    score: 36,
    max_score: 45,
  },
  {
    id: "asm_04",
    user_id: USER_ID,
    subject_id: "sub_chemistry",
    name: "Unit test: Stoichiometry",
    date: "2026-03-04",
    score: 27,
    max_score: 40,
  },
  {
    id: "asm_05",
    user_id: USER_ID,
    subject_id: "sub_chemistry",
    name: "Paper 1 practice",
    date: "2026-06-02",
    score: 24,
    max_score: 40,
  },
  {
    id: "asm_06",
    user_id: USER_ID,
    subject_id: "sub_economics",
    name: "Microeconomics test",
    date: "2026-02-26",
    score: 31,
    max_score: 40,
  },
  {
    id: "asm_07",
    user_id: USER_ID,
    subject_id: "sub_economics",
    name: "Paper 2 practice",
    date: "2026-09-15",
    score: 29,
    max_score: 40,
  },
  {
    id: "asm_08",
    user_id: USER_ID,
    subject_id: "sub_english",
    name: "Paper 1 practice",
    date: "2026-04-22",
    score: 15,
    max_score: 20,
  },
  {
    id: "asm_09",
    user_id: USER_ID,
    subject_id: "sub_arabic",
    name: "Paper 1 practice",
    date: "2026-03-18",
    score: 18,
    max_score: 20,
  },
  {
    id: "asm_10",
    user_id: USER_ID,
    subject_id: "sub_arabic",
    name: "Literary analysis essay",
    date: "2026-09-08",
    score: 27,
    max_score: 30,
  },
  {
    id: "asm_11",
    user_id: USER_ID,
    subject_id: "sub_math",
    name: "Unit test: Functions",
    date: "2026-01-29",
    score: 41,
    max_score: 60,
  },
  {
    id: "asm_12",
    user_id: USER_ID,
    subject_id: "sub_math",
    name: "Unit test: Statistics",
    date: "2026-05-13",
    score: 37,
    max_score: 55,
  },
];

export const mockExtracurriculars: Extracurricular[] = [
  {
    id: "ext_gym",
    user_id: USER_ID,
    name: "Gym",
    days: [0, 1, 2, 3, 4, 5, 6],
    start_time: "18:00",
    duration_minutes: 60,
  },
];

// Last week (Mon 21 to Sun 27 Sep 2026). Some planned sessions have no log,
// the way a real week goes. Nothing is logged yet for the current week.
export const mockStudyLogs: StudyLog[] = [
  { id: "log_01", user_id: USER_ID, subject_id: "sub_math", date: "2026-09-21", minutes: 90 },
  { id: "log_02", user_id: USER_ID, subject_id: "sub_physics", date: "2026-09-21", minutes: 60 },
  { id: "log_03", user_id: USER_ID, subject_id: "sub_math", date: "2026-09-22", minutes: 90 },
  { id: "log_04", user_id: USER_ID, subject_id: "sub_chemistry", date: "2026-09-22", minutes: 60 },
  { id: "log_05", user_id: USER_ID, subject_id: "sub_economics", date: "2026-09-22", minutes: 45 },
  { id: "log_06", user_id: USER_ID, subject_id: "sub_physics", date: "2026-09-23", minutes: 60 },
  { id: "log_07", user_id: USER_ID, subject_id: "sub_math", date: "2026-09-24", minutes: 90 },
  { id: "log_08", user_id: USER_ID, subject_id: "sub_chemistry", date: "2026-09-24", minutes: 60 },
  { id: "log_09", user_id: USER_ID, subject_id: "sub_math", date: "2026-09-26", minutes: 60 },
  { id: "log_10", user_id: USER_ID, subject_id: "sub_arabic", date: "2026-09-26", minutes: 60 },
  { id: "log_11", user_id: USER_ID, subject_id: "sub_math", date: "2026-09-27", minutes: 90 },
  { id: "log_12", user_id: USER_ID, subject_id: "sub_english", date: "2026-09-25", minutes: 60 },
];
